const router = require('express').Router()

router.use('/auth', require('./auth'))
router.use('/user', require('./user'))
router.use('/categories', require('./category'))
router.use('/brands', require('./brand'))
router.use('/products', require('./product'))
router.use('/prices', require('./price'))
router.use('/cart', require('./cart'))
router.use('/orders', require('./order'))
router.use('/membership', require('./membership'))
router.use('/wallet', require('./wallet'))
router.use('/points', require('./points'))
router.use('/messages', require('./message'))
router.use('/banners', require('./banner'))
router.use('/announcements', require('./announcement'))
router.use('/stores', require('./store'))
router.use('/videos', require('./video'))
router.use('/upload', require('./upload'))
router.use('/search', require('./search'))
router.use('/user-stock', require('./userStock'))
router.use('/settings', require('./settings'))
router.use('/scan', require('./scan'))

module.exports = router
