const router = require('express').Router()

router.use('/auth', require('./auth'))
router.use('/dashboard', require('./dashboard'))
router.use('/users', require('./user-manage'))
router.use('/categories', require('./category-manage'))
router.use('/brands', require('./brand-manage'))
router.use('/products', require('./product-manage'))
router.use('/prices', require('./price-manage'))
router.use('/orders', require('./order-manage'))
router.use('/membership', require('./member-manage'))
router.use('/banners', require('./banner-manage'))
router.use('/announcements', require('./announcement-manage'))
router.use('/stores', require('./store-manage'))
router.use('/videos', require('./video-manage'))
router.use('/messages', require('./message-manage'))
router.use('/statistics', require('./statistics'))
router.use('/admins', require('./admin-manage'))
router.use('/roles', require('./role-manage'))
router.use('/permissions', require('./permission-manage'))
router.use('/logs', require('./log-manage'))
router.use('/settings', require('./setting-manage'))
router.use('/upload', require('./upload'))

module.exports = router
